name:                sse-conduit
version:             0.1.0.0
github:              "chrisdone/sse-conduit"
license:             BSD-3-Clause
author:              "Chris Done"
maintainer:          "chris@chrisdone.com"
copyright:           "2025 Chris Done"

extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
- base >= 4.7 && < 5
- conduit
- conduit-extra
- http-conduit
- resourcet
- bytestring
- http-types

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
    - Data.Conduit.SSE

tests:
  sse-conduit-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sse-conduit
    - hspec
